name:
  PackageVar
  #   files: publish/SmittyWerbenJJ.Wardrobe.${{ github.run_number }}.var
on:
  push:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        id: get_version

      - name: Zip the release package
        id: zip
        run: |
          mkdir -p publish/Custom/Scripts/SmittyWerbenJJ/Wardrobe
          cp *.cs publish/Custom/Scripts/SmittyWerbenJJ/Wardrobe/
          cp meta.json publish/
          sed -i 's/v0.0.0/${{ steps.get_version.outputs.VERSION }}/' publish/meta.json
          cd publish
          zip -r "SmittyWerbenJJ.Wardrobe.${{ github.run_number }}.var" *
          mv "SmittyWerbenJJ.Wardrobe.${{ github.run_number }}.var" ../
          

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SmittyWerbenJJ.Wardrobe.${{ github.run_number }}.var
          path: SmittyWerbenJJ.Wardrobe.${{ github.run_number }}.var

      - name: release Artifact
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: SmittyWerbenJJ.Wardrobe.${{ github.run_number }}.var
          name: ${{ github.run_number }}
          tag_name: ${{ github.run_number }}          
